### ISSUE TITLE
Implement short-term measurements

### ISSUE THREAD

**Issue by jjatria** [jjatria/plugin_prosodyad#3]
More than once per non-overlapping interval (say, 0.1s?).

**Comment by pspressman** [comment]
Not sure what's meant here-- could have addressed it in another comment.  Certainly I wouldn't want to measure any finer than 0.1 seconds at this point!

**Comment by jjatria** [comment]
Sure. But we still need to implement those finer measures. So far, it's only once per interval.

**Comment by jjatria** [comment]
Finally implemented in 4732320d!
